version: "3.3"
services:
  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_LOG_LEVEL=DEBUG  # Debug log level
    ports:
      - 5433:5432

  odd-platform:
    image: ghcr.io/opendatadiscovery/odd-platform:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_TYPE=LOGIN_FORM  # Enable Form Login authentication
      - AUTH_LOGIN_FORM_CREDENTIALS=username:passwd # Default credentials
      - LOGGING_LEVEL_ROOT=DEBUG  # Enable debug logging
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG  # Debug logging for Spring Web
    depends_on:
      - database
    ports:
      - 8080:8080

  # Commented out services are omitted for brevity.

  odd-collector:
    image: ghcr.io/opendatadiscovery/odd-collector:latest
    restart: always
    volumes:
      - ./config/collector_config.yaml:/app/collector_config.yaml
    environment:
      - PLATFORM_HOST_URL=${PLATFORM_HOST_URL}
      - LOGLEVEL=DEBUG  # Debug log level
      - TOKEN=${TOKEN}